#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 11 12:49:42 2023

@author: williamagerhall
"""
import random
import string
class PasswordGenerator():
    def __init__(self,name):
        self.name = name
        
        
    def password(self,password):
        num = [0,1,2,3,4,5,6,7,8,9]
        alph = string.ascii_letters
        rand_ord=[0,1]
        i=0
        while i <15:
            hard=random.choice(rand_ord)
            a = random.choice(num)
            b = random.choice(alph)
            
            if hard == 0:
                password = password + str(a) + str(b)
            
            else:
                password=password + str(b) + str(a)
        
            i = i +1
            
        return password
            
            
    def save_new_file(self):
        self.txt = open("password.txt","a")
        name = self.name
        password = self.password("")
        self.txt.write("\n" + str(name) + ": " + str(password))
        self.txt.close()
        
        
    #Detta är en lösen genertaor
         
        
        
        
        
        